config/routes.rb
Rails.application.routes.draw do
  resources :lookups, only: [:create]
  get 'lookup/:token' => 'lookups#show'
  post 'lookups', to: 'lookups#create'
  root 'lookups#new'
  get '*path', to: 'lookups#lookup'
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  include Dictionary

  validates_presence_of :url
  validates_presence_of :token
  validates_uniqueness_of :token
  #validate TODO: validate lenght of token make sure its no over 255

  before_save :prepend_http_protocol
  before_update :prepend_http_protocol

  before_validation :base_36_encode
  before_update :base_36_encode

  def shortify
    loop do
      adj = rand_adj
      next_adj = different_rand_adj(adj)
      word = [adj, next_adj, rand_noun].join('-')
      break word unless Lookup.where(token: word).first.present?
    end
  end

  def prepend_http_protocol
    self.url = "http://#{url}" unless url.index('http://') == 0 || url.index('https://') == 0
  end

  def base_36_encode
    return if token.present?
    self.token = loop do
      random_id = rand(('z' * 8).to_i(36))
      break random_id.to_s(36) unless Lookup.where(token: random_id.to_s(36)).first.present?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  def lookup
    url = Lookup.where('token = ?', request.params['path']).first.try(:url)

    if url.nil?
      flash[:notice] = 'Url not found'
      @lookup = Lookup.new
      render :new and return
    end

    redirect_to url
  end

  def show
    @lookup = Lookup.where('token = ?', params["token"]).first
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  def create
    mode = params[:mode]
    @lookup = Lookup.new(lookup_params)
    @lookup.token = @lookup.shortify if mode == 'shortify'

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to "/lookup/#{@lookup.token}" }
        format.json { render :show, status: :created, location: @lookup }
      else
        format.html { render :new }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def lookup_params
    params.permit(:token, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_form.html.erb
<%= form_tag('lookups', method: 'post') do %>
  <% if @lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% @lookup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= text_field_tag :url, nil, placeholder: 'Paste link here!' %>
  </div>

  <div class="field display-none token-field">
    <%= label_tag "#{request.host_with_port}/" %>
    <%= text_field_tag :token %>
  </div>

    <% select_options = [['Shorten', :shorten], ['Shortify', :shortify], ['Custom', :custom]] %>
    <%= select_tag(:mode, options_for_select(select_options)) %>
  <div class="actions">
    <%= submit_tag 'Hit it!' %>
  </div>
<% end %>

app/views/lookups/edit.html.erb
<h1>Editing lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/index.html.erb
<h1>Listing lookups</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lookups.each do |lookup| %>
      <tr>
        <td><%= lookup.token %></td>
        <td><%= lookup.url %></td>
        <td><%= link_to 'Show', lookup %></td>
        <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
        <td><%= link_to 'Destroy', lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lookup', new_lookup_path %>

app/views/lookups/new.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>

<%= render 'form' %>

<script>
  // TODO: fix back button on isCustom thing!
$(document).ready(function() {
    var $tokenField = $('.token-field')
    var $mode = $('#mode')

    if($mode.find('option:selected').text() == "Custom"){
        $tokenField.removeClass('display-none');
    }

    $mode.change(function(){
        var isCustom = $(this).find('option:selected').text() == "Custom";
        $tokenField.toggleClass('display-none', !isCustom);
    });
});
</script>

app/views/lookups/show.html.erb
<div>
  I got yo link right here!
  <span id="copy-link">
    <% lookup_href = "#{request.host_with_port}/#{@lookup.token}" %>
    <%= link_to(lookup_href, lookup_href, id: 'lookup-link') %>
  </span>
  <button data-clipboard-target='lookup-link' id='copy-button'>Click to copy link</button>
</div>

<div>
  <strong>Links to:</strong>
  <%= link_to(@lookup.url, @lookup.url) %>
</div>

<%= link_to 'Make another?', root_path %>

<script>
$(document).ready(function() {
  var clip = new ZeroClipboard($("#copy-button"));
});
</script>